"""Stable reason codes for MVP-0 ingestion, QC, and MFCV eligibility."""

from __future__ import annotations

from enum import Enum


class QCReasonCode(str, Enum):
    # Import / file
    MANIFEST_NOT_FOUND = "MANIFEST_NOT_FOUND"
    MANIFEST_JSON_INVALID = "MANIFEST_JSON_INVALID"
    SIGNAL_FILE_NOT_FOUND = "SIGNAL_FILE_NOT_FOUND"
    FILE_NOT_READABLE = "FILE_NOT_READABLE"
    CSV_PARSE_ERROR = "CSV_PARSE_ERROR"
    CSV_HEADER_INVALID = "CSV_HEADER_INVALID"

    # Metadata / privacy
    REQUIRED_METADATA_MISSING = "REQUIRED_METADATA_MISSING"
    FORBIDDEN_PHI_KEY_PRESENT = "FORBIDDEN_PHI_KEY_PRESENT"
    UNSUPPORTED_SIGNAL_UNIT = "UNSUPPORTED_SIGNAL_UNIT"
    CHANNEL_COLUMN_MISSING = "CHANNEL_COLUMN_MISSING"
    NO_USABLE_SIGNAL_CHANNEL = "NO_USABLE_SIGNAL_CHANNEL"

    # Time / sampling
    TIME_VALUE_NONFINITE = "TIME_VALUE_NONFINITE"
    TIME_NOT_MONOTONIC = "TIME_NOT_MONOTONIC"
    SAMPLING_RATE_MISMATCH = "SAMPLING_RATE_MISMATCH"
    SAMPLING_RATE_BELOW_PROTOCOL_MIN = "SAMPLING_RATE_BELOW_PROTOCOL_MIN"
    TIMING_JITTER_EXCESSIVE = "TIMING_JITTER_EXCESSIVE"

    # Protocol
    PROTOCOL_NOT_FOUND = "PROTOCOL_NOT_FOUND"
    PROTOCOL_VERSION_MISMATCH = "PROTOCOL_VERSION_MISMATCH"
    ACTIVE_PHASE_MISSING = "ACTIVE_PHASE_MISSING"
    ACTIVE_DURATION_TOO_SHORT = "ACTIVE_DURATION_TOO_SHORT"
    TARGET_MUSCLE_MISMATCH = "TARGET_MUSCLE_MISMATCH"
    REQUIRED_SESSION_PARAMETER_MISSING = "REQUIRED_SESSION_PARAMETER_MISSING"

    # Signal heuristics
    NONFINITE_RATIO_WARNING = "NONFINITE_RATIO_WARNING"
    NONFINITE_RATIO_EXCESSIVE = "NONFINITE_RATIO_EXCESSIVE"
    FLATLINE_SUSPECTED = "FLATLINE_SUSPECTED"
    FLATLINE_EXCESSIVE = "FLATLINE_EXCESSIVE"
    CLIPPING_SUSPECTED = "CLIPPING_SUSPECTED"
    POWERLINE_NOISE_HIGH = "POWERLINE_NOISE_HIGH"
    MOTION_ARTIFACT_HIGH = "MOTION_ARTIFACT_HIGH"
    BASELINE_NOISE_HIGH = "BASELINE_NOISE_HIGH"

    # Capability eligibility
    MFCV_LINEAR_ARRAY_NOT_CONFIRMED = "MFCV_LINEAR_ARRAY_NOT_CONFIRMED"
    MFCV_INTERELECTRODE_DISTANCE_UNKNOWN = "MFCV_INTERELECTRODE_DISTANCE_UNKNOWN"
    MFCV_ORIENTATION_NOT_CONFIRMED = "MFCV_ORIENTATION_NOT_CONFIRMED"
    MFCV_INSUFFICIENT_ADJACENT_CHANNELS = "MFCV_INSUFFICIENT_ADJACENT_CHANNELS"
    MFCV_SAMPLING_RATE_INSUFFICIENT = "MFCV_SAMPLING_RATE_INSUFFICIENT"
    MFCV_ADJACENT_CORRELATION_LOW = "MFCV_ADJACENT_CORRELATION_LOW"

    # Aggregation (DAY30)
    AGGREGATION_THRESHOLD_NOT_VERIFIED = "AGGREGATION_THRESHOLD_NOT_VERIFIED"
    AGGREGATION_INPUT_CONTRADICTION = "AGGREGATION_INPUT_CONTRADICTION"



BLOCKING_CODES: frozenset[QCReasonCode] = frozenset(
    {
        QCReasonCode.MANIFEST_NOT_FOUND,
        QCReasonCode.MANIFEST_JSON_INVALID,
        QCReasonCode.SIGNAL_FILE_NOT_FOUND,
        QCReasonCode.FILE_NOT_READABLE,
        QCReasonCode.CSV_PARSE_ERROR,
        QCReasonCode.CSV_HEADER_INVALID,
        QCReasonCode.REQUIRED_METADATA_MISSING,
        QCReasonCode.FORBIDDEN_PHI_KEY_PRESENT,
        QCReasonCode.UNSUPPORTED_SIGNAL_UNIT,
        QCReasonCode.CHANNEL_COLUMN_MISSING,
        QCReasonCode.NO_USABLE_SIGNAL_CHANNEL,
        QCReasonCode.TIME_VALUE_NONFINITE,
        QCReasonCode.TIME_NOT_MONOTONIC,
        QCReasonCode.SAMPLING_RATE_BELOW_PROTOCOL_MIN,
        QCReasonCode.PROTOCOL_NOT_FOUND,
        QCReasonCode.PROTOCOL_VERSION_MISMATCH,
        QCReasonCode.ACTIVE_PHASE_MISSING,
        QCReasonCode.ACTIVE_DURATION_TOO_SHORT,
        QCReasonCode.NONFINITE_RATIO_EXCESSIVE,
        QCReasonCode.FLATLINE_EXCESSIVE,
    }
)


MFCV_ONLY_CODES: frozenset[QCReasonCode] = frozenset(
    {
        QCReasonCode.MFCV_LINEAR_ARRAY_NOT_CONFIRMED,
        QCReasonCode.MFCV_INTERELECTRODE_DISTANCE_UNKNOWN,
        QCReasonCode.MFCV_ORIENTATION_NOT_CONFIRMED,
        QCReasonCode.MFCV_INSUFFICIENT_ADJACENT_CHANNELS,
        QCReasonCode.MFCV_SAMPLING_RATE_INSUFFICIENT,
        QCReasonCode.MFCV_ADJACENT_CORRELATION_LOW,
    }
)


def is_blocking(code: QCReasonCode) -> bool:
    """Return True when a reason blocks basic MVP-0 sEMG analysis."""
    return code in BLOCKING_CODES


def is_mfcv_only(code: QCReasonCode) -> bool:
    """Return True when a reason disables MFCV but not basic sEMG analysis."""
    return code in MFCV_ONLY_CODES