from __future__ import annotations
from abc import ABC,abstractmethod
from .contracts import *

class AutoDataEvidenceBackend(ABC):
    """Bind to canonical signal/processing/metric/review/audit services. Never store signal samples in audit events."""
    @abstractmethod
    def get_signal_index(self,session_id:str)->SignalIndexOut: ...
    @abstractmethod
    def get_signal_window(self,session_id:str,channel_id:str,*,start_s:float,end_s:float,representation:str)->SignalWindowOut: ...
    @abstractmethod
    def get_processing_manifest(self,manifest_id:str)->ProcessingManifestOut: ...
    @abstractmethod
    def get_session_evidence(self,session_id:str)->SessionEvidenceOut: ...
    @abstractmethod
    def list_review_cases(self,session_id:str|None)->list[ReviewCaseOut]: ...
    @abstractmethod
    def get_review_case(self,case_id:str)->ReviewCaseOut: ...
    @abstractmethod
    def submit_review_action(self,case_id:str,action:ReviewActionIn,*,actor_ref:str|None)->ReviewActionOut: ...
    @abstractmethod
    def get_audit_trail(self,session_id:str)->list[AuditEventOut]: ...
