from pathlib import Path
import hashlib
from typing import Dict, Any

def sha256_file(path: Path) -> str:
    """
    Computes the SHA-256 hash of a file by reading it in chunks.
    This prevents memory exhaustion for large files.
    """
    h = hashlib.sha256()
    with path.open("rb") as f:
        # Read in 1MB chunks
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()

def audit_uv_lock(path: str | Path) -> Dict[str, Any]:
    """
    Audits the uv.lock file to ensure it's generated by the resolver and computes its hash.
    """
    p = Path(path)
    if not p.exists():
        return {"pass": False, "reason": "UV_LOCK_MISSING"}
    
    # Check if the lock file appears to be resolver-generated
    # To avoid memory poisoning on a massive fake lockfile, we only read the first few KB
    with p.open("r", encoding="utf-8", errors="replace") as f:
        head_text = f.read(4096)
    
    if len(head_text) < 100 or "version" not in head_text:
        return {"pass": False, "reason": "UV_LOCK_NOT_RESOLVER_GENERATED"}
        
    return {
        "pass": True, 
        "sha256": sha256_file(p), 
        "bytes": p.stat().st_size
    }
