#!/usr/bin/env python3
"""Optional plotting helper.

This script is intentionally not run by default. It only accepts train/validation statistics
CSV generated by Day29 and never reads raw/sealed-test signal data.
"""
from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--statistics", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    args = parser.parse_args()

    grouped: dict[str, list[float]] = defaultdict(list)
    with args.statistics.open("r", encoding="utf-8-sig", newline="") as handle:
        for row in csv.DictReader(handle):
            grouped[row["day_id"]].append(float(row["rms"]))

    args.output_dir.mkdir(parents=True, exist_ok=True)
    days = sorted(grouped)
    values = [grouped[day] for day in days]
    plt.figure(figsize=(8, 5))
    plt.boxplot(values, tick_labels=days)
    plt.xlabel("Ngày/session")
    plt.ylabel("RMS theo unit đã khai báo")
    plt.title("GRABMyo — phân bố RMS mô tả theo ngày (train/validation)")
    plt.tight_layout()
    plt.savefig(args.output_dir / "rms-by-day.png", dpi=150)
    plt.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
