"""Quality Gate aggregation package."""

from .qc_aggregation import (
    AggregationArchitectureError,
    ChannelCoverageSummary,
    SessionCoverageSummary,
    WindowAssessmentRef,
    WindowDisposition,
    require_final_qc_decision,
    summarize_channel_coverage,
    summarize_session_coverage,
)
from .session_quality import (
    AggregationMetrics,
    AggregationPolicy,
    AggregationPolicyError,
    EvaluationStatus,
    EvidenceStatus,
    IntegrityFinding,
    LabelCandidate,
    QcAggregationResult,
    RawDetectorEvidence,
    ScopeHierarchy,
    SemanticContradictionError,
    SignalQuality,
    Supportability,
    ThresholdStatus,
    WeakLabelCandidate,
    WeakLabelContractError,
    aggregate_channel,
    aggregate_session,
    aggregate_window,
    load_aggregation_policy,
    validate_result_semantics,
)

__all__ = [
    "AggregationArchitectureError",
    "ChannelCoverageSummary",
    "SessionCoverageSummary",
    "WindowAssessmentRef",
    "WindowDisposition",
    "require_final_qc_decision",
    "summarize_channel_coverage",
    "summarize_session_coverage",
    "AggregationMetrics",
    "AggregationPolicy",
    "AggregationPolicyError",
    "EvaluationStatus",
    "EvidenceStatus",
    "IntegrityFinding",
    "LabelCandidate",
    "QcAggregationResult",
    "RawDetectorEvidence",
    "ScopeHierarchy",
    "SemanticContradictionError",
    "SignalQuality",
    "Supportability",
    "ThresholdStatus",
    "WeakLabelCandidate",
    "WeakLabelContractError",
    "aggregate_channel",
    "aggregate_session",
    "aggregate_window",
    "load_aggregation_policy",
    "validate_result_semantics",
]

