"""Compatibility entrypoint cho SpectralEstimator Day 9.

Tên file này được giữ để CLI/tests có một điểm import rõ ràng. Implementation
chính nằm trong ``spectral_estimator.py``.
"""

from spectral_estimator import (  # noqa: F401
    SPECTRAL_COMPUTATION_FAILED,
    SPECTRAL_ESTIMATION_BLOCKED_BY_WINDOWING,
    SPECTRAL_FREQUENCY_AXIS_MISMATCH,
    SPECTRAL_NO_COMPUTED_ROWS,
    SPECTRAL_POWER_TOO_LOW,
    SPECTRAL_PREPROCESS_CONFIG_MISMATCH,
    SPECTRAL_PROFILE_NOT_FOUND,
    SPECTRAL_PROFILE_PURPOSE_MISMATCH,
    SPECTRAL_QA_WARNINGS_PRESENT,
    SPECTRAL_WINDOWING_CONFIG_MISMATCH,
    SPECTRAL_WINDOWS_EXCLUDED,
    SPECTRAL_WINDOW_INVALID,
    SpectralEstimator,
)

# Alias ngắn, giữ tương thích với naming convention của Day 8.
SPECTRAL_BLOCKED_BY_WINDOWING = SPECTRAL_ESTIMATION_BLOCKED_BY_WINDOWING

__all__ = [
    "SpectralEstimator",
    "SPECTRAL_BLOCKED_BY_WINDOWING",
    "SPECTRAL_ESTIMATION_BLOCKED_BY_WINDOWING",
    "SPECTRAL_WINDOWING_CONFIG_MISMATCH",
    "SPECTRAL_PREPROCESS_CONFIG_MISMATCH",
    "SPECTRAL_PROFILE_NOT_FOUND",
    "SPECTRAL_PROFILE_PURPOSE_MISMATCH",
    "SPECTRAL_NO_COMPUTED_ROWS",
    "SPECTRAL_WINDOWS_EXCLUDED",
    "SPECTRAL_COMPUTATION_FAILED",
    "SPECTRAL_WINDOW_INVALID",
    "SPECTRAL_POWER_TOO_LOW",
    "SPECTRAL_QA_WARNINGS_PRESENT",
    "SPECTRAL_FREQUENCY_AXIS_MISMATCH",
]
